#!/bin/bash
# Helper script to set up a test WireGuard configuration

set -e

echo "=== Crabbit WireGuard Test Setup ==="
echo ""

# Check if wg is installed
if ! command -v wg &> /dev/null; then
    echo "Error: wireguard-tools not found. Please install:"
    echo "  Ubuntu/Debian: sudo apt install wireguard-tools"
    echo "  Fedora: sudo dnf install wireguard-tools"
    echo "  macOS: brew install wireguard-tools"
    exit 1
fi

# Generate keys
echo "Generating WireGuard keys for Crabbit..."
PRIVATE_KEY=$(wg genkey)
PUBLIC_KEY=$(echo "$PRIVATE_KEY" | wg pubkey)

echo ""
echo "Generated keys:"
echo "  Private key: $PRIVATE_KEY"
echo "  Public key:  $PUBLIC_KEY"
echo ""

# Get peer info
echo "Now, let's configure your WireGuard peer."
echo ""
read -p "Enter the peer's public key: " PEER_PUBKEY
read -p "Enter the peer's endpoint (IP:port, e.g., 192.168.1.100:51820): " PEER_ENDPOINT
read -p "Enter the peer's WireGuard IP (e.g., 10.0.0.1): " PEER_IP
read -p "Enter Crabbit's WireGuard IP (e.g., 10.0.0.2): " CRABBIT_IP
read -p "Enter Crabbit's listen port [51821]: " LISTEN_PORT
LISTEN_PORT=${LISTEN_PORT:-51821}

# Create test config
cat > test-config.toml <<EOF
# Test configuration generated by setup-test.sh
[listen]
address = "127.0.0.1:5640"

[wireguard]
private_key = "$PRIVATE_KEY"
listen_port = $LISTEN_PORT
address = "$CRABBIT_IP"

[[wireguard.peers]]
name = "test-peer"
public_key = "$PEER_PUBKEY"
endpoint = "$PEER_ENDPOINT"
allowed_ips = ["$PEER_IP/32"]
persistent_keepalive = 25

[dns]
servers = ["8.8.8.8"]

[auth]
mode = "standalone"
authid = "test"
authdom = "test"

[[auth.users]]
name = "test"
key = "0123456789abcdef"
EOF

echo ""
echo "✓ Created test-config.toml"
echo ""

# Generate peer config snippet
cat > peer-config.txt <<EOF
# Add this to your peer's WireGuard configuration:
# (e.g., /etc/wireguard/wg0.conf or via 'wg set' command)

[Peer]
PublicKey = $PUBLIC_KEY
AllowedIPs = $CRABBIT_IP/32
Endpoint = YOUR_CRABBIT_IP:$LISTEN_PORT
# Replace YOUR_CRABBIT_IP with the public IP of the machine running Crabbit

# Or use this command on the peer:
# sudo wg set wg0 peer $PUBLIC_KEY allowed-ips $CRABBIT_IP/32 endpoint YOUR_CRABBIT_IP:$LISTEN_PORT
EOF

echo "✓ Created peer-config.txt with peer configuration"
echo ""

echo "=== Next Steps ==="
echo ""
echo "1. On your peer machine, add the configuration from peer-config.txt"
echo ""
echo "2. Make sure UDP port $LISTEN_PORT is open on this machine:"
echo "   sudo ufw allow $LISTEN_PORT/udp  # Ubuntu/Debian"
echo "   sudo firewall-cmd --add-port=$LISTEN_PORT/udp  # Fedora/RHEL"
echo ""
echo "3. Run the test:"
echo "   cargo run --example test-wg-connection test-config.toml"
echo ""
echo "4. Or with debug logging:"
echo "   RUST_LOG=debug cargo run --example test-wg-connection test-config.toml"
echo ""
echo "Your Crabbit public key: $PUBLIC_KEY"
echo "Share this with your peer!"
